[package]
name = "day9rs"
version = "0.1.0"
authors = ["Roger Lipscombe <roger@differentpla.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
